In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv("spam.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
df.Category.value_counts

<bound method IndexOpsMixin.value_counts of 0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Category, Length: 5572, dtype: str>

In [5]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [6]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [8]:
len(x_train)

4457

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_cv=v.fit_transform(x_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59211 stored elements and shape (4457, 7678)>

In [10]:
x_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7678))

In [11]:
x_train_cv.shape

(4457, 7678)

In [13]:
v.get_feature_names_out()[10:30]

array(['02085076972', '021', '03', '04', '0430', '05', '050703', '0578',
       '06', '07', '07008009200', '07046744435', '07090201529',
       '07090298926', '07099833605', '07123456789', '0721072',
       '07732584351', '07734396839', '07742676969'], dtype=object)

In [14]:
v.vocabulary_

{'sms': 6219,
 'services': 5993,
 'for': 2932,
 'your': 7647,
 'inclusive': 3649,
 'text': 6738,
 'credits': 2074,
 'pls': 5217,
 'goto': 3205,
 'www': 7580,
 'comuk': 1953,
 'net': 4713,
 'login': 4157,
 '3qxj9': 459,
 'unsubscribe': 7128,
 'with': 7484,
 'stop': 6449,
 'no': 4763,
 'extra': 2729,
 'charge': 1735,
 'help': 3394,
 '08702840625': 81,
 '220': 356,
 'cm2': 1872,
 '9ae': 728,
 'hey': 3417,
 'you': 7642,
 'around': 1063,
 've': 7206,
 'got': 3201,
 'enough': 2607,
 'half': 3301,
 'the': 6764,
 'ten': 6716,
 'owe': 4992,
 'message': 4428,
 'responce': 5704,
 'what': 7415,
 'happend': 3321,
 'then': 6774,
 'come': 1912,
 'wenever': 7400,
 'lik': 4089,
 'to': 6878,
 'and': 953,
 'also': 916,
 'tel': 6702,
 'vikky': 7234,
 'by': 1589,
 'getting': 3122,
 'free': 2975,
 'time': 6847,
 'thanks': 6755,
 'subscription': 6518,
 'ringtone': 5751,
 'uk': 7068,
 'mobile': 4513,
 'will': 7456,
 'be': 1267,
 'charged': 1736,
 'month': 4547,
 'please': 5210,
 'confirm': 1965,
 'replying': 

In [16]:
x_train_cp=x_train_cv.toarray()
x_train_cp[:4][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7678,))

In [17]:
np.where(x_train_cp[0]!=0)

(array([  81,  356,  459,  728, 1735, 1872, 1953, 2074, 2729, 2932, 3205,
        3394, 3649, 4157, 4713, 4763, 5217, 5993, 6219, 6449, 6738, 7128,
        7484, 7580, 7647]),)

In [18]:
x_train[:4]

5497    SMS SERVICES. for your inclusive text credits,...
3283    Hey you around? I've got enough for a half + t...
2387               No message..no responce..what happend?
5148    K..then come wenever u lik to come and also te...
Name: Message, dtype: str

In [19]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_cv,y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)Number of samples encountered for each class during fitting. Thisvalue is weighted by the sample weight when provided.","ndarray[float64](2,)","[3855., 602.]"
"class_log_prior_ class_log_prior_: ndarray of shape (n_classes,)Smoothed empirical log probability for each class.","ndarray[float64](2,)","[-0.15,-2. ]"
"classes_ classes_: ndarray of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"feature_count_ feature_count_: ndarray of shape (n_classes, n_features)Number of samples encountered for each (class, feature)during fitting. This value is weighted by the sample weight whenprovided.","ndarray[float64](2, 7678)","[[ 0., 0., 1.,..., 1., 0., 1.], [ 8.,24., 0.,..., 0., 1., 0.]]"
"feature_log_prob_ feature_log_prob_: ndarray of shape (n_classes, n_features)Empirical log probability of featuresgiven a class, ``P(x_i|y)``.","ndarray[float64](2, 7678)","[[-10.97,-10.97,-10.27,...,-10.27,-10.97,-10.27], [ -7.78, -6.76, -9.98,..., -9.98, -9.29, -9.98]]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,7678


In [20]:
x_test_cv=v.transform(x_test)

In [22]:
from sklearn.metrics import classification_report
y_pred=model.predict(x_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       970
           1       0.96      0.90      0.93       145

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [24]:
emails=[
  'Hey mohan, can we get together to watch football game tomorrow',
  'Upto 20% discount on parking, exclusive offer just for you . Dont miss the reward!'
]
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1])