In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)
x_train

array([[ 0.,  0.,  6., ...,  0.,  0.,  0.],
       [ 0.,  0.,  4., ...,  8.,  0.,  0.],
       [ 0.,  0.,  9., ...,  3.,  0.,  0.],
       ...,
       [ 0.,  0.,  2., ...,  6.,  0.,  0.],
       [ 0.,  0.,  9., ..., 16., 16.,  5.],
       [ 0.,  4., 14., ..., 11.,  0.,  0.]], shape=(1257, 64))

In [24]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Taimour Khokhar\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [25]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [26]:
rf=RandomForestClassifier(n_estimators=10)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9222222222222223

In [27]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [28]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [31]:
def get_score(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)
  

In [35]:
get_score(SVC(),x_train,x_test,y_train,y_test)


0.987037037037037

In [36]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)


C:\Users\Taimour Khokhar\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [37]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)


0.9777777777777777

In [38]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)


In [47]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
  x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  
  scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
  scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators=50),x_train,x_test,y_train,y_test))
  

C:\Users\Taimour Khokhar\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Taimour Khokhar\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-

In [48]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [49]:
scores_rf

[0.9198664440734557, 0.9432387312186978, 0.9315525876460768]

In [50]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [53]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\Taimour Khokhar\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Taimour Khokhar\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [54]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [55]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92222222, 0.88611111, 0.95821727, 0.96657382, 0.92200557])