In [3]:
import numpy as np

In [4]:
revenue=np.array([[180,200,220],[24,36,40],[12,18,20]])
expense=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [5]:
profit=revenue-expense

In [6]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [7]:
price_per_unit=np.array([1000,400,1200])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [9]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [12]:
Revenue_in_dollar=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
inr=75

In [13]:
Revenue_in_inr=inr*Revenue_in_dollar
Revenue_in_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [ ]:
flowers=np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit=np.array([[20],[30],[15]])


In [46]:
flowers.shape
price_per_unit.shape

(3,)

In [ ]:
final=flowers*price_per_unit
final

array([[1000, 1800,  375],
       [ 200,  390,   75],
       [ 800, 2100,  780]])