In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
  print("Gpu is avialable")
  print(f"using gpu : {torch.cuda.get_device_name(0)}")
else:
  print("Gpu is not avialable")

Gpu is avialable
using gpu : Tesla T4


In [5]:
#Creating a tensor

#using empty
a=torch.empty(2,3)
type(a)

torch.Tensor

In [7]:
#using zeros
b=torch.zeros(2,3)
b
type(b)

torch.Tensor

In [8]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using random
torch.rand(2,3)

tensor([[0.7532, 0.3862, 0.9028],
        [0.4516, 0.5162, 0.6885]])

In [15]:
#using seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
#using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
#arange
print("using arrange ",torch.arange(0,10,2))

#using linspace
print("using linspace ", torch.linspace(0,10,10))

#using eye
print("using eye ",torch.eye(5))

#using full
print("using full", torch.full((3,3),5))

using arrange  tensor([0, 2, 4, 6, 8])
using linspace  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [21]:
#Tensor Shapes
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [22]:
torch.empty_like(x)

tensor([[             126176,                  36,                   0],
        [                  0, 4604268618497130496, 3545238235232953957]])

In [24]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [26]:
#find data type
x.dtype

torch.int64

In [27]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [30]:
#using to()
x.to(torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [31]:
#Mathematiccal operations
x=torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [32]:
e=torch.randint(size=(2,3),low=0,high=10)
e

tensor([[4, 3, 8],
        [8, 4, 4]])

In [34]:
torch.sum(e)

tensor(31)

In [35]:
torch.sum(e,dim=0)

tensor([12,  7, 12])

In [36]:
torch.sum(e,dim=1)

tensor([15, 16])

In [37]:
torch.median(e)

tensor(4)

In [39]:
torch.min(e)

tensor(3)

In [41]:
torch.argmax(e)

tensor(2)

In [44]:
#inplcae operations
m=torch.rand(2,3)
n=torch.rand(2,3)
print(n)
print(m)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [45]:
m+n

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [46]:
m.add_(n)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [47]:
m

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [48]:
#copying a tensor
a=torch.rand(2,3)
a

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [49]:
b=a
b

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [50]:
a[0][0]=0
a

tensor([[0.0000, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [51]:
b

tensor([[0.0000, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [52]:
id(a)

132396891799328

In [53]:
id(b)

132396891799328

In [54]:
b=a.clone()
b

tensor([[0.0000, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [55]:
a

tensor([[0.0000, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [56]:
b

tensor([[0.0000, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [57]:
id(a)

132396891799328

In [58]:
id(b)

132396894065184

In [59]:
#tensor opeartions on gpu
torch.cuda.is_available()

True

In [60]:
device=torch.device('cuda')

In [61]:
torch.rand([2,3],device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [62]:
#moving existinig tensor to gpu
a=torch.rand([2,3])
a

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [63]:
a.to(device)

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]], device='cuda:0')

In [64]:
#reshaping tensors
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [65]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [66]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
b=torch.rand(2,3,4)
b

tensor([[[0.5163, 0.0359, 0.6476, 0.3430],
         [0.3182, 0.5261, 0.0447, 0.5123],
         [0.9051, 0.5989, 0.4450, 0.7278]],

        [[0.4563, 0.3389, 0.6211, 0.5530],
         [0.6896, 0.3687, 0.9053, 0.8356],
         [0.3039, 0.6726, 0.5740, 0.9233]]])

In [70]:
#permute
b.permute(2,0,1).shape


torch.Size([4, 2, 3])

In [74]:
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [75]:
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])